service: sls-access-counter

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.conf.tableName}"

functions:
  counter:
    handler: handler.counter
    events:
      - http:
          path: counter
          method: get
          cors: true

resources:
  Resources:
    CounterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.conf.tableName}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  conf: ${file(conf/config.json)}